### ISSUE TITLE
Add verbose mode to StormBehaviour_pt

### ISSUE THREAD

**Issue by thomasarsouze** [umr-amap/StormR#12]
For the sake of consistency with other functions, add a verbose mode to function `StormBehaviour_pt`. According to #9, depending on the timing on solving the issues, the function name might have changed to `TemporalBehaviour`.

**Comment by BaptisteDlp** [comment]
Seems useless to me as this function is really fast ??

**Comment by thomasarsouze** [comment]
I as more refering to the same behaviour as `spatialBehaviour`:
```
    cat("=== temporalBehaviour processing ... ===\n\n")

    cat("Computation settings:\n")
    ...
```

**Comment by BaptisteDlp** [comment]
Alright  I'm on it then, no need to print output though
