### ISSUE TITLE
Add PlotStorms

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#2]
# Description

Plot location(s) of interest (LOI) or area of interest (AOI) together with storm trajectories with administrative boundaries

# Usage

 `PlotStorms(Obj = …, )`

# Arguments

Obj  : an object generated with the get Storm 

# Exemples

 `plot(StormsLoc1)`
`plot(StormsSP)`

**Comment by thomasarsouze** [comment]
Done
