### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#24]
J'ai installé la dernière version à partir de la master et j'ai les fonction help qui ne marchent pas

?plotBehaviour
Error in fetch(key) : 
  lazy-load database '/home/ibanez/R/x86_64-pc-linux-gnu-library/4.2/StormR/help/StormR.rdb' is corrupt
?spatialBehaviour
Internal Server Error

**Comment by BaptisteDlp** [comment]
Oui @thomasarsouze  m'en a parlé, et même quand on veut lancer les exemples via rstudio ça ne marche pas, il y a effectivement quelque chose qui ne fonctionne pas mais je ne sais pas quoi encore ...

**Comment by thomasarsouze** [comment]
Problème non reproductible.
` lazy-load database '/home/ibanez/R/x86_64-pc-linux-gnu-library/4.2/StormR/help/StormR.rdb' is corrupt` implique souvent un redémarrage de Rstudio.
