### ISSUE TITLE
MSW

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#26]
st <- Storms(loi = "Vanuatu", names = "PAM")
ss <- spatialBehaviour(st,product=c("MSW","PDI","Exposure"),verbose=0)
plotBehaviour(st,ss$PAM_MSW)

Bug on a des taches blanches (des NA?) dans la carte de MSW avec le paramétrage par défault

**Comment by BaptisteDlp** [comment]
ça vient du range de vent pour le produit MSW dans plotBehaviour qui était de base réglé à 18 -80 m/s. Avec les nouvelles formules d'asymétries ça augmente les valeurs de msw et on se retrouve pour les cyclones les plus puissants avec des valeurs au dessus de 80m/s ... Je trouve ça un peu abérrant et c'est ce que j'essayais de t'expliquer la denrière fois,
En tout cas il suffit juste de chager le range

**Comment by thomaspibanez** [comment]
Ok je comprends maintenant tu as donc des MSW qui sont supérieurs au MSW affichés dans la BDD. C'est bizarre mais pas forecément abérant car le MSW de la BDD n'est pas mesuré mais estimé à partir d'un modèle je pense... en fouillant un peu j'ai trouvé que le max enregistré est 345 km h ~ 95 m.s-1 du coup oui on peut augmenter le range de la barre de couleur à 95 ou 100 m.s-1

**Comment by BaptisteDlp** [comment]
Fix commit  'e6e944a066ca8a80f6dac2eadf4c871fb8a9f359'
