### ISSUE TITLE
échelle couleur spatialBehaviour

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#27]
Se superpose sur l'axe des x

st <- Storms(loi = "Vanuatu", names = "PAM")
ss <- spatialBehaviour(st,product=c("MSW","PDI","Exposure"),verbose=0)
plotBehaviour(st,ss$PAM_MSW)

**Comment by BaptisteDlp** [comment]
Un peu tricky à gérer la place de la légende, je pense que le changement de marge y est aussi pour quelque chose je regarderai

**Comment by BaptisteDlp** [comment]
Fix in 07c9c1122399c902b48f366538be39b6fbec5525
