### ISSUE TITLE
plotBehaviour gestion des "main"

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#28]
Dans plotBehaviour il y a des titres ("main")
Pour PDI ajouter l'unité (comme pour MSW et Exposure)
Pour Exposure remplacer "Time spent" par "Duration of exposure"
Pour les profils mettre en majuscule la première lettre

On ne peut pas choisir de les modifier ou de les supprimer
plotBehaviour(st,ss$PAM_Exposure_58,main="test")
Error in plotBehaviour(st, ss$PAM_Exposure_58, main = "test") : 
  unused argument (main = "test")

**Comment by BaptisteDlp** [comment]
Fix in commit bc907e39c33c423a4ed822ff492fdc372113325a
