### ISSUE TITLE
Help spatialBehaviour and temporalBehaviour

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#29]
Il faut expliquer (peut être dans une section details) comment est faite l'interpolation des observations (passage d'une observation toute les 3 h pour IBTrACKS à des données toutes les heures ou moins en fonction de la résolution choisie)

**Comment by BaptisteDlp** [comment]
Fix in commit  552393eb63bc0ae4fecef0deb19e1899f432c51c
