### ISSUE TITLE
Rename test dataset

### ISSUE THREAD

**Issue by thomasarsouze** [umr-amap/StormR#32]
As we decided to simplify the test / example dataset, It makes sense to change the name from "South Pacific storms database" / "IBTRACS_SP" to "test_dataset" or simply "test".

In the reference document, https://umr-amap.github.io/StormR/reference/IBTRACS_SP.html, add the references of IBTRACS and the date of use of IBTRACS.

**Comment by BaptisteDlp** [comment]
What are the 2 references to add ? You sent them to me but I don't remember where ...

**Comment by BaptisteDlp** [comment]
Fix in commit 51f9d74e54df12c42cb6322190dd071763bb2aca

**Comment by BaptisteDlp** [comment]
Ok found it
