### ISSUE TITLE
plotStorms category

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#34]
pt <- c(166.45,-22.27)
st <- Storms(loi = pt)
plotStorms(st, category = c(4,5), labels=TRUE)
Error in which(sts@sshs >= cat.inf & sts@sshs <= cat.sup) : 
  no slot of name "sshs" for this object of class "StormsList"

**Comment by BaptisteDlp** [comment]
Fix in commit 1099318fd19555078328017bd3042ed975f01142
