### ISSUE TITLE
getNames outputs

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#35]
Un peu bizarre le format de sortie de getNames
Si j'ai bien compris c'est un vecteur de NOMS mais aussi avec le noms des NOMS  

pt <- c(166.45,-22.27)
st <- Storms(loi = pt, seasons = c(2015,2021), verbose=0)
getNames(st)
SOLO   GRETEL    LUCAS    NIRAN 
"SOLO" "GRETEL"  "LUCAS"  "NIRAN" 

Est-ce que c'est pas bon d'avoir simplement qq chose du genre
test<-getNames(st)
names(test)<-NULL
test
"SOLO"   "GRETEL" "LUCAS"  "NIRAN"

**Comment by BaptisteDlp** [comment]
Fix in commit  f14f655fbc5568f6c0f4203d1245153e25bfcf08
