### ISSUE TITLE
plotStorms category filter

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#36]
sp <- eezNC
st <- Storms(loi = eezNC, season=c(2015,2021),verbose=0)
plotStorms(st, category = c(4,5), labels=TRUE)
Error in which(sts@sshs >= cat.inf & sts@sshs <= cat.sup) : 
  no slot of name "sshs" for this object of class "StormsList"

**Comment by BaptisteDlp** [comment]
Fix in commit 1099318fd19555078328017bd3042ed975f01142
