### ISSUE TITLE
Problem plotStorms

### ISSUE THREAD

**Issue by BaptisteDlp** [umr-amap/StormR#37]
### What is your issue?

I removed reset_setting argument, but the solution with the margins (**par(mar=...)**) does not work so I decided not to change it.
However, there seem to be a bug: Sometimes, some lands are plotted outside of the extent of the plot. I was able to manage it by changing the margin sizes but that was random and incomprehensible ... 
I do not know how to fix this issue that appears randomly. Maybe we should find another package to plot the land ... For the moment we use **maps::map()**

**Comment by thomaspibanez** [comment]
What about plot(...)? with add=TRUE if necessary?

**Comment by BaptisteDlp** [comment]
Cf issue #43
