### ISSUE TITLE
Check examples on Help

### ISSUE THREAD

**Issue by BaptisteDlp** [umr-amap/StormR#38]
### What is your issue?

I think we should check and fix examples in the Helps for every functions once for all:
- Storms()
- plotStorms()
- spatialBehaviour()
- temporalBehaviour()
- writeRast()
- defDatabase()

knowing that we have the following toy/examples provided by the package:

- test_dataset:  TC nearby Vanuatu from 2015 to 2016 + TC nearby New Caledonia from 2020 to 2021
- pam: Pam data nearby Vanuatu
- sts_nc extraction of test_dataset nearby New Caledonia
- eezNC: economic exclusize zone of New Caledonia

Any suggestions ?

**Comment by BaptisteDlp** [comment]
toy/examples data*

**Comment by thomaspibanez** [comment]
Ok I will do that once I'm done with the vignettes. I should be able to do that by the end of the week.

**Comment by thomasarsouze** [comment]
I've put back the netcdf file of `test_dataset` in `data` directory because somehow it has been deleted by an earlier commit.
I think we could get rid of `pam` and `sts_nc` as they're included in `test_dataset`. This means checking the documentation and vignettes.

Also, do we need to keep `eezNC` ? I guess we could specify how to retrieve it in a vignette or reference ?

**Comment by BaptisteDlp** [comment]
I deleted `test_dataset.nc `but forgot to put it back ...
Check this link to have informations about how to handle data in a R package. 
I think you should put it back in `inst/extdata`

I agree with Thomas I. we should keep `eezNC`, it is usefull to run the examples (in `Storms()`) and we can use it in our tests

**Comment by thomasarsouze** [comment]
Done in #48 for `test_dataset.nc`.
@thomaspibanez once you're ok with the examples, we still need to remove pam and sts_nc from `data` and `data-raw`

**Comment by BaptisteDlp** [comment]
Done in commit b421e61f0585979120413bab02d62837909fe0d7

No more `pam`, `sts_nc` and `test_database`

I modified the examples, you can check if there are ok for you.
Nevertheless, @thomasarsouze , there seems to be a probleme in your` test_dataset.nc` 
I had some errors that I should not have when testing the database if you gathered the correct storms ?

**Comment by BaptisteDlp** [comment]
problem*

**Comment by thomaspibanez** [comment]
Les examples dans les vignettes n'avaient pas été modifié c'est pour cela peut être qu'il y avait des erreurs. J'ai fait les modifs et pushé
