### ISSUE TITLE
defDatabase 

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#39]
### What is your issue?

Dans defDatabase le basin par default est tjrs SP.

Par exemple si j'importe tous les tempêtes des 3 dernières années à travers le monde avec les arguments par default

download.file(url = "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/netcdf/IBTrACS.last3years.v04r00.nc", destfile = "./IBTrACS_ALL_3yrs.nc")

sds <- defDatabase(filename = "IBTrACS_ALL_3yrs.nc", verbose = TRUE)

sds@basin
"SP"

REMPLACER par basin=NULL comme indiqué dans la doc

**Comment by BaptisteDlp** [comment]
C'était fait dans la master mais il fallait pull dans la  branch vignette
J'ai rendu le champs basin optionnel aussi et j'ai rajouté un input seasons pour filtrer la base de donnée selon un range de saisons (au lieu de le faire dans Storms, ça évite des bugs et c'est plus propre)
