### ISSUE TITLE
[New Feature]: Change the reference wind scale

### ISSUE THREAD

**Issue by thomasarsouze** [umr-amap/StormR#40]
### Describe your feature request

So far, only the Saffir Simpson scale is defined and can be used to filter by category. It would be good to let the user define his own scales / categories.

### Describe the solution you'd like

Let the sshs defined by default with its own category names (-1, 0,...) and values (18, 33, ...). 
Build a more general wrapping that can let the user add its own category names and values and pass it as arguments of the functions.

**Comment by BaptisteDlp** [comment]
I think this feature might be done within the plot functions (category input ). These are routines that let the user filter by category, alongside with behavior functions but in these ones, the `windThreshold` input already let the user choose for its own scale
