### ISSUE TITLE
[New Feature]: Export SotrmsList object

### ISSUE THREAD

**Issue by thomasarsouze** [umr-amap/StormR#42]
### Describe your feature request

After loading and filtering a database, we have a stormsList object that we can't directly export. It would be good to have the possibility to export either as a netcdf or .csv file 

### Describe the solution you'd like

A writeStormsList function , e.g. `writeStormsList(pam, filename)`,  that detects the extension of the file and writes it as netcdf or csv

**Comment by BaptisteDlp** [comment]
Do you mean a StormsDataset ? 
Whether it is a StormsList or a StormsDataset, saving data in R can be easily achieved using save() or saveRDS() functions ...
