### ISSUE TITLE
Strange behaviour margin 

### ISSUE THREAD

**Issue by BaptisteDlp** [umr-amap/StormR#43]
### What is your issue?

 When calling a plotStorms for the first time, default margin is  **par$mar == c(5.1, 4.1, 4.1, 2.1)**. This setting let the extra land outside of the plot be visible (that is not what we want). Nevertheless, this setting automatically change to **par$mar == c(4.1, 4.1, 4.1, 0.1)** afterwards and it is no longer a problem.

There seem to be something strange even if it resolves an issue

**Comment by thomasarsouze** [comment]
I think this issue is no longer relevant and can therefore be closed. What do you think @BaptisteDlp ?

**Comment by BaptisteDlp** [comment]
It might be outdated now, I checked with the new version, I think everything is fine now with `plotStorms`
