### ISSUE TITLE
HELP temporalBehaviour et spatialBehaviour functions

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#47]
### What is your issue?

Dans le détail de l'help il faut ajouter comme dans la vignette modèles les descriptions et equation des modèles. On peut faire un copié-collé mais je ne suis pas certain que le format suive. Je te laisse voir ça Baptiste.

**Comment by BaptisteDlp** [comment]
Je pense pas qu'il faille mettre ça dans le help, ça risque d'etre très lourd, et les équations je sais pas si ça se fait en général de mettre ça dans les helps. Peut  être quelques mots sur les modèles et renvoyer le user vers la vignette models ? @thomasarsouze ?

**Comment by BaptisteDlp** [comment]
Fix commit 62bca28cbd2009dfaf16047c9e1d6b70dca191b2
