### ISSUE TITLE
"test_dataset.nc" et exemples

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#48]
### What is your issue?

Je ne vois pas bien comment utiliser le fichier NetCDF dans les examples car dans defDatabase() il faut lui fournir un lien vers un fichier nc (character)

Quand on charge le paquet library(StormR) on a directement accès aux objets R de data : test_dataset, pam, eezNC, sts_nc... mais je ne vois pas comment on accède à "test_dataset.nc"?

Du coup je me demande si il ne faut pas laisser les examples comme tel sans passer par le NetCDF?

**Comment by thomasarsouze** [comment]
Pas encore eu le temps de faire, mais:
- comme dit par @BaptisteDlp dans [#38], il faut mettre le fichier dans `inst/extdata`
- Pour accéder aux fichiers dans `inst/extdata`, il faut faire `system.file("extdata", "test_dataset.nc", package = "StormR")`
- Pour bien faire il faudrait (?) changer [cette ligne](https://github.com/umr-amap/StormR/blob/155149540d80fdf608e102d63dcb6ef34b434e34/R/stormsDataset.R#L279) et la doc en mettant par défaut  `filename = system.file("extdata", "test_dataset.nc", package = "StormR")` et donc changer aussi les exemples

**Comment by thomaspibanez** [comment]
Ok je verrai pour changer/ajouter les exemples quand le fichier sera dans inst/extdata ça me dépasse un peu

**Comment by thomasarsouze** [comment]
Done change file location in ca04edfb225338eacb43d3eba474995073d1f208 .
Done `test_dataset.nc` as default filename for `defDatabase` in 48c8227ebe5a6b6a623cb31227d16ff0631d4701
```R
> test <- defDatabase()
=== Loading data  ===
Open database... /Library/Frameworks/R.framework/Versions/4.2/Resources/library/StormR/extdata/test_dataset.nc opened
Collecting data ...
=== DONE ===
```

**Comment by BaptisteDlp** [comment]
Il faut donc changer la fonction` Storm()` et rendre mandatory l'argument `sds`, sinon ça va buger

**Comment by thomasarsouze** [comment]
> Il faut donc changer la fonction` Storm()` et rendre mandatory l'argument `sds`, sinon ça va buger

Exact. That's what we decided at some point when we where talking about the dataset: in the examples, we wanted the full workflow (i.e. including the `defDatabse`) ans make de `stormsList` object mandatory in the `Storms` request.

@BaptisteDlp, I saw that you did that work in b421e61f0585979120413bab02d62837909fe0d7 . Can we close this issue ?

**Comment by BaptisteDlp** [comment]
Fixed with issue #53
