### ISSUE TITLE
defDatabase basin

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#51]
### What is your issue?

C'est normal que dans defDatabase il n'y a plus basin dans les champs à définir? Je me demande si c'est pas pour ça qu'il y a des examples qui bug?

defDatabase <- function(filename=system.file("extdata", "test_dataset.nc", package = "StormR"),
                        fields = c(names = "name",
                                   seasons = "season",
                                   isoTime = "iso_time",
                                   lon = "usa_lon",
                                   lat = "usa_lat",
                                   msw = "usa_wind",
                                   sshs = "usa_sshs",
                                   rmw = "usa_rmw",
                                   pressure = "usa_pres",
                                   poci = "usa_poci"),
                        basin = NULL,
                        seasons = c(1980, as.numeric(format(Sys.time(), "%Y"))),
                        unit_conversion = c(msw = "knt_to_ms",
                                            rmw = "nm_to_km",
                                            pressure = "mb_to_pa",
                                            poci = "mb_to_pa"),
                        verbose = TRUE)

**Comment by thomasarsouze** [comment]
I don't think we want that, otherwise the package will always look for a `basin` field and fail if it can't find it (and if there is not such type of information in the databse).
What makes you think this raises bugs ? Which bugs ?

**Comment by BaptisteDlp** [comment]
Fixed commit 7bbeec1d0a1813e377f8c909752cfbdf6d06a74d
