### ISSUE TITLE
Misunderstanding in documentation??

### ISSUE THREAD

**Issue by BaptisteDlp** [umr-amap/StormR#54]
### What is your issue?

I saw your changes in the getters function. 

When you say "By default all storms occurring since 1980 are extracted." It is true that this is the default setting. Nevertheless this fliter is performed in `defDatabase` when extracting data and no longer in `Storms`.

**Comment by BaptisteDlp** [comment]
Another thing: It is best to avoid **"The ... function allows"** sentences in the description of functions

**Comment by thomaspibanez** [comment]
Changed
