### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BaptisteDlp** [umr-amap/StormR#55]
### What is your issue?

We have to get rid of these warnings/notes

❯ checking Rd cross-references ... WARNING
  Missing link or links in documentation object 'spatialBehaviour.Rd':
    ‘0027:LARIOH’
  
  Missing link or links in documentation object 'temporalBehaviour.Rd':
    ‘0027:LARIOH’
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.

❯ checking Rd line widths ... NOTE
  Rd file 'getSSHS-methods.Rd':
    \examples lines wider than 100 characters:
       #Getting maximum Saffir-Simpson hurricane wind scale category reached by each storm in the sts object 
  
  Rd file 'writeRast.Rd':
    \examples lines wider than 100 characters:
       #Getting storm track data for tropical cyclone Pam (2015) near Vanuatu and computing maximum sustained wind speed

**Comment by thomaspibanez** [comment]
I don't understand I did the changes but the warnings are still there... Can you try baptist to update the doc?
