### ISSUE TITLE
[Bug]: temporalBehaviour() doesn't accept negative long value 

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#59]
### What happened?

Error in checkInputsTempBehaviour(sts, points, product, wind_threshold,  : 
  Invalid points coordinates

### Minimal Complete Verifiable Example

```R
IBTrACS<-defDatabase("IBTrACS.ALL.v04r00.nc",verbose=FALSE)
pts<-c(-76.66790,18.09773)
st<-Storms(IBTrACS,loi=pts,seasons=1988,names="GILBERT",verbose=0)
pts<-data.frame(x=-76.66790,y=18.09773)
temp<-temporalBehaviour(st,pts,product=c("TS"),verbose=0)
```

### Propose a solution

implement automatic conversion if Lon < 0 then Lon = Lon + 360 as in the Storms function

### Environment

<details>

</details>

**Comment by BaptisteDlp** [comment]
Fixed in commit 90a1c16038428d2e8cac085eb38d0e56ea602bb4
