### ISSUE TITLE
[New Feature]: add overwrite argument for writeRast()

### ISSUE THREAD

**Issue by epingchris** [umr-amap/StormR#64]
### Describe your feature request

As it seems that the writeRast() function calls terra::writeRaster(), it could be a good idea to also include the overwrite argument that exists in terra::writeRaster(), so that they could follow the similar syntax.

**Comment by thomasarsouze** [comment]
Default was set to `overwrite = TRUE`. 

In commit dbfdd649535f8d8b61edf7ff679eee8caaba6412, we changed this and now `writeRast` function allows any argument that can be passed to [`terra::writeRaster()` function](https://rdrr.io/cran/terra/man/writeRaster.html). 

This implies that now the default behaviour is `overwrite = FALSE`.
