### ISSUE TITLE
[Bug]: error when seasons argument in Storms() function is outside the time range of StormsDataset object

### ISSUE THREAD

**Issue by epingchris** [umr-amap/StormR#65]
### What happened?

When I supply a year range that is not entirely contained within the database for the seasons argument in the Storms(), it results in the following error message:

Error in checkInputsGs(sds, loi, seasons, names, max_dist, verbose, remove_TD) : 
  lower bound of time range is not valid

or

Error in checkInputsGs(sds, loi, seasons, names, max_dist, verbose, remove_TD) : 
  upper bound of time range is not valid

I understand that it might not technically be a bug, but is the intended behavior of the function. Nevertheless, I do feel that from the user's perspective, it would be more convenient if the function can automatically deal with any time range and return, whether or not there is any storms within that range or if the provided range is completely within the time range of the database.

### Minimal Complete Verifiable Example

```R
library(StormR)
storm_db = defDatabase(verbose = F)
str(storm_db) #season min: 2015, max: 2021
storm_list = Storms(storm_db, loi = "Vanuatu", seasons = c(2014, 2016), verbose = 0) #shows error
storm_list = Storms(storm_db, loi = "Vanuatu", seasons = c(2015, 2022), verbose = 0) #shows error
```

### Propose a solution

When the time range provided in the seasons argument is not completely within the time range of the database, use only the intersection of the two.

### Environment

<details>

‘0.1.0’

</details>

**Comment by thomasarsouze** [comment]
Hi @epingchris. 

I don't think we want to change this behaviour. By doing so, the user might expect to have all storms in the time interval provided in argument, even though this could not be the case if the `stormsDataset` is not defined accordingly.

Right now, we improved the error message and decided not to change the code. 

If in the future, this behaviour finds to be unpractical to other users, we might consider changing the error message to a warning and implement your solution.

Closing the issue.
