### ISSUE TITLE
Interactive plot with leaflet

### ISSUE THREAD

**Issue by BaptisteDlp** [umr-amap/StormR#7]
Problem with leaflet dependencies (raster rather than terra) to plot legend in plotBehaviour function.
Issue in fixPlotLegend branch.

**Comment by thomasarsouze** [comment]
@BaptisteDlp can you provide a simple reproducible exemple and point to the code where you have the problem ?

**Comment by thomasarsouze** [comment]
Considering the developments done since the opening of this issue, the branch should be updated and this feature tested again.

**Comment by BaptisteDlp** [comment]
@thomasarsouze @thomaspibanez ,
The interactive mode in `plotstorm()` works perfectly fine from now (I changed few things in my local branch),

Do you think it is interesting to have an interactive version of `plotBehaviour()` ? The problem actually still remains the same for the dependency with raster lib and not terra
