### ISSUE TITLE
Swaped columns in temporalBehavior output

### ISSUE THREAD

**Issue by BaptisteDlp** [umr-amap/StormR#71]
### What is your issue?

In the third data frame (point3) from the following output for `temporalBehavior` function, 'speed' and 'direction' columns have been swaped for some unknown reasons ...

`df <- data.frame(x = c(168.33,
                        167.17,
                       169.17),
                 y = c(-17.73,
                       -15.53,
                       -15.53))
pointNames <- c("Port_Vila",
               "Luganville",
               "point3")

cols <- c("blue", "red", "gray")

rownames(df) <- pointNames

sds <- defStormsDataset()

st <- defStormsList(sds = sds, loi = "Vanuatu", names = "PAM", verbose = 1)

plotStorms(st)
points(df$x, df$y, pch = 3, col = cols)
text(df$x, df$y, labels = pointNames, pos = 2, col = cols, cex = 0.8)

TS <- temporalBehaviour(st, points = df, product = "TS", tempRes = 0.5, verbose = 0)`

**Comment by thomasarsouze** [comment]
Solved in [a2c5577](https://github.com/umr-amap/StormR/commit/a2c55779183bcd5dcc31bc81aefb9bc30dfc9478).
