### ISSUE TITLE
[Bug]: getScale function not working

### ISSUE THREAD

**Issue by riskiem** [umr-amap/StormR#82]
### What happened?

I tired the following code= using the getScale() function.I get error: Error in getScale(st3) : could not find function "getScale"

### Minimal Complete Verifiable Example

```R
download.file(url = "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/netcdf/IBTrACS.since1980.v04r00.nc", destfile = "./IBTrACS_Since1980.nc")
sds <- defStormsDataset(filename = "./IBTrACS_Since1980.nc", basin = NULL, verbose = 0)
str(sds)
st3 <-defStormsList(sds = sds, loi = "Mexico",  seasons = c(2000, 2020) ,verbose = 2)
getScale(st3)
```

### Propose a solution

I should be able to see the scale of the storm

### Environment

<details>

‘0.1.1’

</details>

**Comment by BaptisteDlp** [comment]
Your code above works fine for me, Have you downloaded the newest version of the package ? We have recently added some new features and functionalities.
Maybe you should try the following:

- Uninstall StormR
- Install the latest development version with `devtools::install_github("umr-amap/StormR")`

**Comment by thomasarsouze** [comment]
No reply. Closing the issue.
Please reopen if the bug is still present.
