### ISSUE TITLE
[Bug]: StormR:::getDataInterpolate fails with fractional time difference between initial storm readings

### ISSUE THREAD

**Issue by jbcannon** [umr-amap/StormR#86]
### What happened?

`StormR:::getDataInterpolate` creates a time differences variable `dt` based on time difference from the first two readings, and it generates an interpolated dataset which is longer based on settings for the temporal resolution. But when the difference is in fractions of hours (e.g., 2.5 hours), this method fails.  For example for 2018 FAY in NA basin. 

### Minimal Complete Verifiable Example

```R
input_nc_file = 'hurrecon-global/data/IBTrACS.ALL.v04r00.nc' #download from IBTracks
stormsDataset = StormR::defStormsDataset(input_nc_file, basin='NA', seasons=c(2008,2008))
stormsList = StormR::defStormsList(na_sds, names='FAY', loi = 'NA')
StormR::spatialBehaviour(stormsList)
```

### Propose a solution

expand rows independently based on difference between times

### Anything else we need to know?

I think that HURDAT usually uses a 6-hour time interval, but the very first reading may based on the time of the first recording. In some casees, this may differ from the 6 hour intervals (0000, 0600, 1200, and 1800).

### Environment

<details>
‘0.1.1’
</details>

**Comment by thomasarsouze** [comment]
Thanks @jbcannon for submitting this issue... and sorry for the delay in providing the bugfix.
`FAY` is quite a nasty example: 1) irregular observations, 2) on fractions of hours, 3) with sometimes very short time intervals between observation (e.g. 15mn !). All these cases should be handled safely now.

You can test the patch by getting the new `master` version. Hopefully new version on CRAN should come soon.
