### ISSUE TITLE
[Bug]: Issue with dynamic plots in plotBehaviour

### ISSUE THREAD

**Issue by thomaspibanez** [umr-amap/StormR#91]
### What happened?

When the storm overlap with 180E their is an issue with the display of the wind fields using the dynamic plot option in the plotBehaviour function.

### Minimal Complete Verifiable Example

```R
library(StormR)

sds <- defStormsDataset("/Users/ibanezthomas/Documents/IBTrACS.SP.v04r01.nc",
                        basin="SP")

sds <- defStormsList(sds,loi="Fiji",maxDist = 500, names = "WINSTON")

plotStorms(sds)
plotStorms(sds)

ss <- spatialBehaviour(sds, product = "MSW", verbose = 0)

plotBehaviour(sds,ss)

plotBehaviour(sds,ss, dynamicPlot = T)
```

### Environment

<details>

</details>

**Comment by thomasarsouze** [comment]
I can reproduce the bug, thanks for spotting that. 

I can't dedicate time for this right now. Maybe @BaptisteDlp knows a simple and quick way to correct this ? Otherwise I'll look at it after holiday break...

**Comment by BaptisteDlp** [comment]
I have not found any solutions yet. I think it requires some tricks to rebuild the raster around the 180E limit in order to handle the overlap
